[package]
name = "clpack"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
lazy_static = "1.5.0"
termion = "4.0.2"
tokio = { version = "1.39.2", features = ["full"] }
zstd = "0.13.2"
